bDelta_ = 
T1*	( Theta_[0] + Theta_[1]*l1 + Theta_[2]*l2
	+ Theta_[3]*pow(l1,2) + Theta_[4]*l1*l2 + Theta_[5]*pow(l2,2)
	+ Theta_[6]*pow(l1,3) + Theta_[7]*pow(l1,2)*l2 + Theta_[8]*l1*pow(l2,2) + Theta_[9]*pow(l2,3)
	+ Theta_[10]*pow(l1,4) + Theta_[11]*pow(l1,3)*l2 + Theta_[12]*pow(l1,2)*pow(l2,2) + Theta_[13]*l1*pow(l2,3) + Theta_[14]*pow(l2,4)
	+ Theta_[15]*pow(l1,5) + Theta_[16]*pow(l1,4)*l2 + Theta_[17]*pow(l1,3)*pow(l2,2) + Theta_[18]*pow(l1,2)*pow(l2,3) + Theta_[19]*l1*pow(l2,4) + Theta_[20]*pow(l2,5)
	+ Theta_[21]*pow(l1,6) + Theta_[22]*pow(l1,5)*l2 + Theta_[23]*pow(l1,4)*pow(l2,2) + Theta_[24]*pow(l1,3)*pow(l2,3) + Theta_[25]*pow(l1,2)*pow(l2,4) + Theta_[26]*l1*pow(l2,5) + Theta_[27]*pow(l2,6))

+T2*( Theta_[28] + Theta_[29]*l1 + Theta_[30]*l2
	+ Theta_[31]*pow(l1,2) + Theta_[32]*l1*l2 + Theta_[33]*pow(l2,2)
	+ Theta_[34]*pow(l1,3) + Theta_[35]*pow(l1,2)*l2 + Theta_[36]*l1*pow(l2,2) + Theta_[37]*pow(l2,3)
	+ Theta_[38]*pow(l1,4) + Theta_[39]*pow(l1,3)*l2 + Theta_[40]*pow(l1,2)*pow(l2,2) + Theta_[41]*l1*pow(l2,3) + Theta_[42]*pow(l2,4)
	+ Theta_[43]*pow(l1,5) + Theta_[44]*pow(l1,4)*l2 + Theta_[45]*pow(l1,3)*pow(l2,2) + Theta_[46]*pow(l1,2)*pow(l2,3) + Theta_[47]*l1*pow(l2,4) + Theta_[48]*pow(l2,5)
	+ Theta_[49]*pow(l1,6) + Theta_[50]*pow(l1,5)*l2 + Theta_[51]*pow(l1,4)*pow(l2,2) + Theta_[52]*pow(l1,3)*pow(l2,3) + Theta_[53]*pow(l1,2)*pow(l2,4) + Theta_[54]*l1*pow(l2,5) + Theta_[55]*pow(l2,6))


+T3*( Theta_[56] + Theta_[57]*l1 + Theta_[58]*l2
	+ Theta_[59]*pow(l1,2) + Theta_[60]*l1*l2 + Theta_[61]*pow(l2,2)
	+ Theta_[62]*pow(l1,3) + Theta_[63]*pow(l1,2)*l2 + Theta_[64]*l1*pow(l2,2) + Theta_[65]*pow(l2,3)
	+ Theta_[66]*pow(l1,4) + Theta_[67]*pow(l1,3)*l2 + Theta_[68]*pow(l1,2)*pow(l2,2) + Theta_[69]*l1*pow(l2,3) + Theta_[70]*pow(l2,4)
	+ Theta_[71]*pow(l1,5) + Theta_[72]*pow(l1,4)*l2 + Theta_[73]*pow(l1,3)*pow(l2,2) + Theta_[74]*pow(l1,2)*pow(l2,3) + Theta_[75]*l1*pow(l2,4) + Theta_[76]*pow(l2,5)
	+ Theta_[77]*pow(l1,6) + Theta_[78]*pow(l1,5)*l2 + Theta_[79]*pow(l1,4)*pow(l2,2) + Theta_[80]*pow(l1,3)*pow(l2,3) + Theta_[81]*pow(l1,2)*pow(l2,4) + Theta_[82]*l1*pow(l2,5) + Theta_[83]*pow(l2,6));